#%RAML 1.0
title: Patron Services
baseUri: https://github.com/folio-org/mod-patron
protocols: [ HTTPS ]
version: v4.2

documentation:
  - title: Patron Services
    content: |
      This module allows 3rd party discovery services to perform patron
      actions in FOLIO

types:
  account: !include account.json
  hold: !include hold.json
  loan: !include loan.json
  charge: !include charge.json
  money: !include money.json
  item: !include item.json
  external_patron: !include external_patron.json
  external_patron_collection: !include external_patron_collection.json
  user: !include userdata.json
  allowedServicePoints: !include allowed-service-points-response.json
  errors: !include raml-util/schemas/errors.schema
  error: !include raml-util/schemas/error.schema
  parameters: !include raml-util/schemas/parameters.schema

traits:
  validate: !include raml-util/traits/validation.raml

/patron:
  displayName: Patron Services
  description: |
    Services that allow patron empowerment from 3rd party discovery services
  /account:
    post:
      description: |
        Creates external patron request
      is: [validate]
      body:
        application/json:
          type: external_patron
          example: !include examples/external_patron.json
      responses:
        201:
          description: |
            Returns data for a new hold request on the selected item
          body:
            application/json:
              type: external_patron
              example: !include examples/external_patron.json
        400:
          description: Bad request
          body:
            text/plain:
              example: unable to process request
        422:
          description: Validation error
          body:
            application/json:
              type: errors
        500:
          description: |
            Internal server error, e.g. due to misconfiguration
          body:
            text/plain:
              example: internal server error, contact administrator
    get:
      description: Return external_patrons detail
      queryParameters:
        expired:
          description: |
            Indicates to return only expired patron
          required: false
          type: boolean
          default: false
      responses:
        200:
          description: Returns the external patron accounts collection
          body:
            application/json:
              type: external_patron_collection
              example: !include examples/external_patron_collection.json
        400:
          description: Bad request
          body:
            text/plain:
              example: unable to process request -- constraint violation
        500:
          description: Internal server error, e.g. due to misconfiguration
          body:
            text/plain:
              example: internal server error, contact administrator
    /by-email/{emailId}:
      displayName: Get Accounts By email
      description: Service endpoints that manage accounts by an existing email
      uriParameters:
        emailId:
          description: The email of external patron
          type: string
      put:
        description: |
          Updates external patron request
        is: [validate]
        body:
          application/json:
            type: external_patron
            example: !include examples/external_patron.json
        responses:
          204:
            description: updates external patron
          400:
            description: Bad request
            body:
              text/plain:
                example: unable to process request
          404:
            description: Item with a given ID not found
            body:
              text/plain:
                example: item not found
          422:
            description: Validation error
            body:
              application/json:
                type: errors
          500:
            description: |
              Internal server error, e.g. due to misconfiguration
            body:
              text/plain:
                example: internal server error, contact administrator
    /registration-status/{emailId}:
      description: endpoint that can be used to fetch a patron by email
      uriParameters:
        emailId:
          description: The email ID of the patron.
          type: string
          required: true
      get:
        description: Get the patron details by email ID
        responses:
          200:
            description: patron information retrieved successfully
            body:
              application/json:
                type: user
                example: !include examples/user.json
          400:
            description: Validation error
            body:
              application/json:
                type: errors
          404:
            description: Validation error
            body:
              application/json:
                type: errors
          500:
            description: Internal server error, e.g. due to misconfiguration
            body:
              text/plain:
                example: internal server error, contact administrator
    /{id}:
      displayName: Manage Accounts By Id
      description: Service endpoints that manage accounts by an existing Id
      uriParameters:
        id:
          description: The UUID of a FOLIO user
          type: string
          pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
      get:
        description: Return account details for the specified FOLIO user id
        queryParameters:
          includeLoans:
            description: |
              Indicates whether or not to include the loans array in
              the response
            required: false
            type: boolean
            default: false
          includeCharges:
            description: |
              Indicates whether or not to include the charges array in
              the response
            required: false
            type: boolean
            default: false
          includeHolds:
            description: |
              Indicates whether or not to include the holds array in
              the response
            required: false
            type: boolean
            default: false
          sortBy:
            description: |
              Part of CQL query, indicates the order of records within the lists of holds, charges, loans
            example: item.title/sort.ascending
            required: false
            type: string
          offset:
            description: Skip over a number of elements by specifying an offset value for the query
            type: integer
            required: false
            example: 0
            default: 0
            minimum: 0
            maximum: 2147483647
          limit:
            description: Limit the number of elements returned in the response
            type: integer
            required: false
            example: 10
            default: 2147483647
            minimum: 0
            maximum: 2147483647
        responses:
          200:
            description: Returns the user account info
            body:
              application/json:
                type: account
                example: !include examples/account.json
          400:
            description: Bad request
            body:
              text/plain:
                example: unable to process request -- constraint violation
          401:
            description: Not authorized to perform requested action
            body:
              text/plain:
                example: unable to get account -- unauthorized
          404:
            description: Item with a given ID not found
            body:
              text/plain:
                example: account not found
          422:
            description: Validation error
            body:
              application/json:
                type: errors
          403:
            description: Access Denied
            body:
              text/plain:
                example: Access Denied
          500:
            description: Internal server error, e.g. due to misconfiguration
            body:
              text/plain:
                example: internal server error, contact administrator
      /item:
        /{itemId}:
          uriParameters:
            itemId:
              description: The UUID of a FOLIO item
              type: string
              pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
          /renew:
            displayName: Renew a Loan
            description: Service endpoint for loan renewal
            post:
              description: Renews a loan on the item for the user
              is: [validate]
              responses:
                201:
                  description: Returns the renewed loan data
                  body:
                    application/json:
                      type: loan
                      example: !include examples/loan.json
                400:
                  description: Bad request
                  body:
                    text/plain:
                      example: unable to process request -- constraint violation
                401:
                  description: Not authorized to perform requested action
                  body:
                    text/plain:
                      example: unable to renew loan -- unauthorized
                404:
                  description: Item with a given ID not found
                  body:
                    text/plain:
                      example: item not found
                403:
                  description: Access Denied
                  body:
                    text/plain:
                      example: Access Denied
                409:
                  description: Conflict
                  body:
                    text/plain:
                      example: Optimistic Locking Conflict
                500:
                  description: |
                    Internal server error, e.g. due to misconfiguration
                  body:
                    text/plain:
                      example: internal server error, contact administrator
          /hold:
            displayName: Hold Management
            description: Services that provide hold management
            post:
              description: |
                Creates a hold request on an existing item for the user
              is: [validate]
              body:
                application/json:
                  type: hold
                  example: !include examples/hold.json
              responses:
                201:
                  description: |
                    Returns data for a new hold request on the specified item
                  body:
                    application/json:
                      type: hold
                      example: !include examples/hold.json
                400:
                  description: Bad request
                  body:
                    text/plain:
                      example: unable to process request -- constraint violation
                401:
                  description: Not authorized to perform requested action
                  body:
                    text/plain:
                      example: unable to create hold -- unauthorized
                404:
                  description: Item with a given ID not found
                  body:
                    text/plain:
                      example: item not found
                403:
                  description: Access Denied
                  body:
                    text/plain:
                      example: Access Denied
                409:
                  description: Conflict
                  body:
                    text/plain:
                      example: Optimistic Locking Conflict
                500:
                  description: |
                    Internal server error, e.g. due to misconfiguration
                  body:
                    text/plain:
                      example: internal server error, contact administrator
            /{holdId}:
              displayName: Hold Management By Id
              description: Services that provide hold management by Id
              uriParameters:
                holdId:
                  description: The UUID of a FOLIO hold request
                  type: string
                  pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
      /instance:
        /{instanceId}:
          uriParameters:
            instanceId:
              description: The UUID of a FOLIO instance
              type: string
              pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
          /hold:
            displayName: Hold Management
            description: Services that provide hold management
            post:
              description: |
                Creates a hold request on an existing item by instance ID for the user
              is: [validate]
              body:
                application/json:
                  type: hold
                  example: !include examples/hold.json
              responses:
                201:
                  description: |
                    Returns data for a new hold request on the selected item
                  body:
                    application/json:
                      type: hold
                      example: !include examples/hold.json
                400:
                  description: Bad request
                  body:
                    text/plain:
                      example: unable to process request -- constraint violation
                401:
                  description: Not authorized to perform requested action
                  body:
                    text/plain:
                      example: unable to create hold -- unauthorized
                404:
                  description: Instance with a given ID not found
                  body:
                    text/plain:
                      example: item not found
                403:
                  description: Access Denied
                  body:
                    text/plain:
                      example: Access Denied
                409:
                  description: Conflict
                  body:
                    text/plain:
                      example: Optimistic Locking Conflict
                500:
                  description: |
                    Internal server error, e.g. due to misconfiguration
                  body:
                    text/plain:
                      example: internal server error, contact administrator
          /allowed-service-points:
            displayName: Allowed service points
            description: Services that provides a list of allowed pickup service points
            get:
              description: |
                Returns a list of pickup service points allowed for a particular patron and instance
              is: [ validate ]
              responses:
                200:
                  description: |
                    Successfully returns a list of allowed service points
                  body:
                    application/json:
                      type: allowedServicePoints
                      example: !include examples/allowed-service-points-response.json
                422:
                  description: Validation error
                  body:
                    application/json:
                      type: errors
                500:
                  description: |
                    Internal server error, e.g. due to misconfiguration
                  body:
                    text/plain:
                      example: internal server error, contact administrator
      /hold:
        displayName: Hold Management
        description: Services that provide hold management
        /{holdId}:
          uriParameters:
            holdId:
              description: The UUID of a FOLIO hold request
              type: string
              pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
          /cancel:
            post:
              description: cancels the request
              body:
                application/json:
                  type: hold
                  example: !include examples/hold.json
              responses:
                200:
                  description: |
                    Returns an updated hold request after cancelling
                  body:
                    application/json:
                      type: hold
                      example: !include examples/hold.json
                400:
                  description: Bad request
                  body:
                    text/plain:
                      example: |
                        unable to process request -- constraint violation
                401:
                  description: Not authorized to perform requested action
                  body:
                    text/plain:
                      example: unable to cancel hold -- unauthorized
                403:
                  description: Access Denied
                  body:
                    text/plain:
                      example: access denied
                404:
                  description: Item with a given ID not found
                  body:
                    text/plain:
                      example: hold not found
                409:
                  description: Conflict
                  body:
                    text/plain:
                      example: Optimistic Locking Conflict
                422:
                  description: Validation error
                  body:
                    application/json:
                      type: errors
                500:
                  description: |
                    Internal server error, e.g. due to misconfiguration
                  body:
                    text/plain:
                      example: internal server error, contact administrator

